version: '3.1'
services:
  mongo:
    # This image automatically creates a replica set required for transactions
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      INIT_WAIT_SEC: 3
    ports:
      - 27017:27017
  api:
    image: nest-pnpm-docker
    build: .
    depends_on:
      - mongo
    ports:
      - 3000:3000